[package]
name = "whir-common"
description = "Common code for verifier and prover"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
ark-ff = { workspace = true }
ark-crypto-primitives = { workspace = true }
spongefish = { workspace = true }
ark-poly = { workspace = true }
spongefish-pow = { workspace = true }
ark-serialize = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
blake3 = { workspace = true }
rayon = { version = "1.10.0", optional = true }
tracing = { version = "0.1.41", optional = true }

[features]
default = ["parallel"]
asm = ["ark-ff/asm"]
parallel = [
    "dep:rayon",
    "ark-poly/parallel",
    "ark-ff/parallel",
    "ark-crypto-primitives/parallel",
]
rayon = ["dep:rayon"]
tracing = ["dep:tracing"]